# Generated by Django 4.2.7 on 2023-12-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
